services:
  caddy:
    build:
      dockerfile: Dockerfile.caddy
      args:
        DNS_PROVIDER: ${DNS_PROVIDER}
    restart: unless-stopped
    networks:
      - net
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    environment:
      CADDY_ADMIN: 0.0.0.0:2019

volumes:
  caddy-data:
  caddy-config:

